<?php

namespace AppBundle\Repository;


/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function pastEvent()
    {
        $query = $this->createQueryBuilder('e')
        ->where('e.date > :date')
        ->setParameter('date', '22/10/2018')
        ->getQuery();

        $query_events = $query->getResult();
    }
    
    
}
